package com.server.calendarapp.pojo;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.google.api.client.auth.oauth2.StoredCredential;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.time.Instant;

@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "GoogleCredential")
public class GoogleCredential {

    private String key;
    private String userID;
    private String accessToken;
    private String refreshToken;
    private String expirationTime;
    private String createdAt;
    private String updatedAt;

    public GoogleCredential(String key, StoredCredential credential) {
        this.userID = key;
        this.accessToken = credential.getAccessToken();
        this.expirationTime = credential.getExpirationTimeMilliseconds().toString();
        this.refreshToken = credential.getRefreshToken();
        this.createdAt = Instant.now().toString();
        this.updatedAt = Instant.now().toString();
    }

    public void apply(StoredCredential credential) {
        this.accessToken = credential.getAccessToken();
        this.expirationTime = credential.getExpirationTimeMilliseconds().toString();
        this.refreshToken = credential.getRefreshToken();
        this.updatedAt = Instant.now().toString();
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = "key")
    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    @DynamoDBAttribute(attributeName = "userID")
    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    @DynamoDBAttribute(attributeName = "accessToken")
    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    @DynamoDBAttribute(attributeName = "refreshToken")
    public String getRefreshToken() {
        return refreshToken;
    }

    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    @DynamoDBAutoGeneratedTimestamp
    @DynamoDBAttribute(attributeName = "createdAt")
    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    @DynamoDBAttribute(attributeName = "updatedAt")
    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    @DynamoDBAttribute(attributeName = "expirationTime")
    public String getExpirationTime() {
        return expirationTime;
    }

    public void setExpirationTime(String expirationTime) {
        this.expirationTime = expirationTime;
    }
}
